### ISSUE TITLE
src/asf_meta/distortions.c relies on a non-public part of the PROJ.4 API

### ISSUE THREAD

**Issue by ninneman** [asfadmin/ASF_MapReady#128]
src/asf_meta/distortions.c relies on parts of the PROJ.4 API that are considered internal, and so this code is fragile, subject to breakage when PROJ.4 changes.

1) The projects.h header is private, and shouldn't be included.
2) The function map_distortions() at one point attempts to directly access the members of a projPJ structure. This is considered bad practice by the PROJ.4 team, since the members are internal and subject to change.

Attempting to fix problem 1 causes compilation errors related to problem 2.
